// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pvfctyslqrtinghvdtma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2ZmN0eXNscXJ0aW5naHZkdG1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNTE3MzcsImV4cCI6MjA2MTkyNzczN30.OwJtvVaCM6UjaaUCVZuBd7k6loyfLeMl22xDQ-RRp70";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);